
version: "2"
linters:
  default: all
  disable:
    - containedctx
    - cyclop
    - depguard
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gocognit # check once in a while
    - goconst
    - gomodguard # deprecated in v2.12.0
    - ireturn
    - lll
    - mnd
    - paralleltest
    - testpackage
    - thelper
    - wrapcheck
    - wsl
  settings:
    dupl:
      threshold: 200
    goconst:
      min-len: 2
      min-occurrences: 4
    gocyclo:
      min-complexity: 45
    gosec:
      excludes:
        - G704
        - G706
    nestif:
      min-complexity: 10
    varnamelen:
      ignore-names:
        - err
        - id
        - i
        - j
        - s
        - tt
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
