# Make sure to enable 'Require status checks to pass before merging' on the branch protection,
# and to select the 'gofmt_check' action.

name: Formatting Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"

permissions: {}

jobs:
  gofmt_check:
    runs-on: ubuntu-latest
    if: github.actor != 'renovate[bot]'

    steps:
      - name: Checkout main
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: "go.mod"

      - name: Run go fmt
        run: |
          if [ -n "$(go fmt ./...)" ]; then
            echo "The following files are not formatted correctly:"
            go fmt ./...
            exit 1
          fi
